### ISSUE TITLE
Allow user to specify minefield size and number of mines

### ISSUE THREAD

**Issue by hzhao90** [duanduan2015/Termine#17]
Command arguments to be supported:
- For standard sizes:
  Termine --standard easy/medium/hard
- For customized sizes:
  Termine --size 5x5 --density 20%

**Comment by duanduan2015** [comment]
Fixed in different way:
python3 Termine.py customized w h n
python3 Termine.py easy/medium/hard

**Comment by duanduan2015** [comment]
Fixed in different way:
python3 Termine.py customized <width> <height> <numOfMines>
python3 Termine.py easy/medium/hard
