### ISSUE TITLE
Rename 'const.py' package

### ISSUE THREAD

**Issue by hzhao90** [duanduan2015/Termine#24]
Rename it to Const.py (with a capital 'C'), or Consts.py, or something else to make it in less similar style with built-in modules.

Also, the name "const" may become deviated from it's semantic if we later allow user to customize the visual styles.

**Comment by hzhao90** [comment]
Please put the commit number that fixes this issue here

**Comment by duanduan2015** [comment]
commit(4d180e8b0111deed19b22f1d746fa5bf625af4d9 ) resolved this issue
